on: [push]

jobs:
  config_push_job:
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - name: Push config
        id: config
        uses: dietergoetelen/env-variables
        with:
          app-name: test
        env:
          FOO_BAZ: true
          FOO_BAR: false
          FOO_NUM: 1
