on: [push]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm ci

  push_config:
    strategy:
      matrix:
        appName: [foo, bar]
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - name: Push config
        uses: ./
        with:
          app-name: ${{ appName }}
        env:
          ENV_KEY1: true
          ENV_KEY2: false
          ENV_KEY3: 1
          ENV_KEY4: "Ok"
