on: [push]

jobs:
  config_push_job:
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push config
        id: config
        uses: ./lib/main.js
        with:
          app-name: test
        env:
          FOO_BAZ: true
          FOO_BAR: false
          FOO_NUM: 1
