on: [push]

jobs:
  push_config:
    strategy:
      matrix:
        appName:
          [
            strobbo-api-001,
            strobbo-api-002,
            strobbo-api-003,
            strobbo-api-004,
            strobbo-api-005,
            strobbo-api-006,
          ]
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push config
        id: config
        uses: ./
        with:
          app-name: ${{ matrix.appName }}
        env:
          ENV_BAZ: true
          ENV_BAR: false
          ENV_NUM: 1
          ENV_STRING: "OK"
          ENV_DIMONA_DB: ${{ secrets.DIMONA_DB }}
