on: [push]

jobs:
  config_push_job:
    runs_on: ubuntu_latest
    name: Push config
    steps:
      - name: Push config
        id: config
        uses: dietergoetelen/env-variables@v1
        with:
          app-name: test
        env:
          configuration:
            foo: 1
            bar: "ok"
            baz: true
