on: [push]

jobs:
  push_config:
    strategy:
      matrix:
        appName: ["kudos-app"]
    runs-on: ubuntu-latest
    name: Push config
    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push config
        id: config
        uses: ./
        with:
          app-name: ${{ matrix.appName }}
        env:
          ENV_STROBBO_DB: ${{ secrets.STROBBO_DB }}

          ENV_APPINSIGHTS_INSTRUMENTATIONKEY: a47c96f6-e775-439d-84fd-4d84ed2e186c
          ENV_APPINSIGHTS_PROFILERFEATURE_VERSION: "1.0.0"
          ENV_APPINSIGHTS_SNAPSHOTFEATURE_VERSION: "1.0.0"
          ENV_APPLICATIONINSIGHTS_CONFIGURATION_CONTENT: ""
          ENV_APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          ENV_ApplicationInsightsAgent_EXTENSION_VERSION: "~3"
          ENV_DiagnosticServices_EXTENSION_VERSION: "~3"
          ENV_DOCKER_REGISTRY_SERVER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}
          ENV_DOCKER_REGISTRY_SERVER_URL: "https://acrkudos.azurecr.io"
          ENV_DOCKER_REGISTRY_SERVER_USERNAME: "acrkudos"
          ENV_InstrumentationEngine_EXTENSION_VERSION: "disabled"
          ENV_SnapshotDebugger_EXTENSION_VERSION: "disabled"
          ENV_WEBSITES_ENABLE_APP_SERVICE_STORAGE: false
          ENV_XDT_MicrosoftApplicationInsights_BaseExtensions: "disabled"
          ENV_XDT_MicrosoftApplicationInsights_Mode: "recommended"
          ENV_XDT_MicrosoftApplicationInsights_PreemptSdk: "disabled"
